spring:
  datasource:
    url: ${JDBC_CONNECTION_STRING}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}

sentry:
  dsn: https://69937d625752d2187b32da40786195c7@o4506235423424512.ingest.sentry.io/4506235432730624
  sentry.traces-sample-rate: 1.0